# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

In [2]:
import numpy as np

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

Return evenly spaced numbers over a specified interval.

Different than arrange as it gives you a range of numbers that are evenly spaced by the 3rd argument

In [17]:
# so, 3 numbers evenly spread b/t 0 and 10
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

Square matrix w/ diagonal of 1s

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [20]:
np.random.rand(2)

array([0.09003896, 0.06245744])

In [21]:
np.random.rand(5, 5)

array([[0.74768907, 0.0264374 , 0.60708217, 0.29663096, 0.97613313],
       [0.17575155, 0.6978339 , 0.54913117, 0.16319925, 0.53481869],
       [0.20831843, 0.75849771, 0.42491636, 0.49484452, 0.46215438],
       [0.86571956, 0.86117812, 0.43518661, 0.51342022, 0.02620356],
       [0.01071844, 0.79524665, 0.83674758, 0.56165867, 0.49292821]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [22]:
np.random.randn(2)

array([0.03108624, 0.93747731])

In [23]:
np.random.randn(5, 5)

array([[ 0.02750953,  0.85172888, -0.81649059, -0.3330713 , -0.77169088],
       [ 0.24135424,  1.22817592, -0.41267865,  0.67123984, -1.27083033],
       [ 0.36012153,  0.13307725, -0.03697601, -0.16256966,  0.40665678],
       [ 0.3404773 , -1.16846912,  0.76253209, -1.02451   ,  0.03855616],
       [-0.83617727,  0.16209639, -0.61925692, -0.88985504,  0.35437248]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [24]:
np.random.randint(1, 100)

2

In [25]:
np.random.randint(1, 100, 10)

array([38, 47, 88,  5, 45,  3, 66, 72, 74, 85])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([31,  9, 23, 30, 17, 30, 24,  1, 13, 43])

## Reshape
Returns an array containing the same data with a new shape.

In [29]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [30]:
ranarr

array([31,  9, 23, 30, 17, 30, 24,  1, 13, 43])

In [31]:
ranarr.max()

43

In [32]:
ranarr.argmax()

9

In [33]:
ranarr.min()

1

In [34]:
ranarr.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [35]:
# Vector
arr.shape

(25,)

In [36]:
# Notice the two sets of brackets
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1, 25).shape

(1, 25)

In [38]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25, 1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [40]:
arr.dtype

dtype('int32')